# Social Network Ads Purchase Prediction

## Goal
The goal of this project is to predict whether a user will purchase a product based on their gender, age, and estimated salary.

## Dataset
The dataset contains the following columns:
- Gender
- Age
- EstimatedSalary
- Purchased

## Model Used
I used Logistic Regression because this is a binary classification problem.

## Result
The model achieved around 88% accuracy on the test data.

In [61]:
import pandas as pd
import numpy as np

In [62]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [63]:
df = pd.read_csv('Social_Network_Ads.csv')

In [64]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [65]:
df.drop(columns=['User ID'], inplace=True)

In [66]:
df

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [67]:
df.isna().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [68]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['Purchased']),
                                                 df['Purchased'],
                                                 test_size = 0.2,
                                                 random_state = 42,
                                                 stratify=df['Purchased'])

In [81]:
X_test

     Gender  Age  EstimatedSalary
331  Female   48           119000
92     Male   26            15000
1      Male   35            20000
234  Female   38           112000
136  Female   20            82000
..      ...  ...              ...
393    Male   60            42000
151    Male   41            45000
126    Male   42            65000
265  Female   42           108000
286  Female   37            62000

[80 rows x 3 columns]

In [70]:
trf1 = ColumnTransformer([
    ('ohe_gender',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[0])
],remainder='passthrough')

In [71]:
trf1

ColumnTransformer(remainder='passthrough',
                  transformers=[('ohe_gender',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 [0])])

In [72]:
df

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [73]:
trf2 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,3))
])

In [74]:
trf3 = LogisticRegression()

In [75]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3)
])

In [76]:
# train
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_gender',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [0])])),
                ('trf2',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 3, None))])),
                ('trf3', LogisticRegression())])

In [77]:
pipe.named_steps

{'trf1': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_gender',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [0])]),
 'trf2': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 3, None))]),
 'trf3': LogisticRegression()}

In [78]:
y_pred = pipe.predict(X_test)

In [79]:
y_pred

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0])

In [80]:
accuracy_score(y_test,y_pred)

0.875

In [84]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[48  3]
 [ 7 22]]
              precision    recall  f1-score   support

           0       0.87      0.94      0.91        51
           1       0.88      0.76      0.81        29

    accuracy                           0.88        80
   macro avg       0.88      0.85      0.86        80
weighted avg       0.88      0.88      0.87        80

## Conclusion

The Logistic Regression model achieved an accuracy of 88% on the test data.  
The model performed well in predicting users who did not purchase, with a recall of 94% for class 0.  
For users who purchased, the recall was 76%, meaning the model correctly identified most buyers but missed some.  

Overall, this is a good baseline classification model for predicting whether a user will purchase based on gender, age, and estimated salary.